baseurl = "/"
defaultContentLanguage = "en"
destination = "../dist/"
disableKinds = ["taxonomy", "taxonomyTerm"]
enableEmoji = true
hrefTargetBlank = false
languageCode = "en-us"
languageLang = "en"
relativeURLs = false
title = "The Proficient Engineer"
theme = "sawmill"
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1
[params]
author = "Socratees Samipillai"
description = "Notes & Observations"
